src/Entity/Transaction.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\TransactionRepository")
 */
class Transaction
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="decimal", precision=12, scale=2)
     */
    private $amount;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $is_input;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $is_valid;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\Column(type="datetime")
     */
    private $updated_at;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Category", inversedBy="transactions")
     * @ORM\JoinColumn(nullable=false)
     */
    private $category_id;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Tag", inversedBy="transactions")
     */
    private $tags;

    public function __construct()
    {
        $this->tags = new ArrayCollection();

        $this->created_at = new \DateTime();
        $this->updated_at = new \DateTime();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function __tostring(){
        return $this->title;
    }

    public function getAmount()
    {
        return $this->amount;
    }

    public function setAmount($amount): self
    {
        $this->amount = $amount;

        return $this;
    }

    public function getIsInput(): ?bool
    {
        return $this->is_input;
    }

    public function setIsInput(?bool $is_input): self
    {
        $this->is_input = $is_input;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getIsValid(): ?bool
    {
        return $this->is_valid;
    }

    public function setIsValid(?bool $is_valid): self
    {
        $this->is_valid = $is_valid;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    public function getCategoryId(): ?Category
    {
        return $this->category_id;
    }

    public function setCategoryId(?Category $category_id): self
    {
        $this->category_id = $category_id;

        return $this;
    }

    /**
     * @return Collection|Tag[]
     */
    public function getTags(): Collection
    {
        return $this->tags;
    }

    public function addTag(Tag $tag): self
    {
        if (!$this->tags->contains($tag)) {
            $this->tags[] = $tag;
        }

        return $this;
    }

    public function removeTag(Tag $tag): self
    {
        if ($this->tags->contains($tag)) {
            $this->tags->removeElement($tag);
        }

        return $this;
    }
}

src/Form/TransactionType.php
<?php

namespace App\Form;

use App\Entity\Transaction;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\MoneyType;

class TransactionType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title', null, ['label' => 'Titre'])
            ->add('amount', MoneyType::class)
            ->add('is_input', null, ['label' => 'Entrée'])
            ->add('description', null, ['label' => 'Description'])
            ->add('is_valid', null, ['label' => 'Valide?'])
            //->add('created_at')
            //->add('updated_at')
            ->add('category_id', null, ['label' => 'Catégories'])
            ->add('tags', null, ['label' => 'Tags'])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Transaction::class,
        ]);
    }
}

src/Controller/TransactionController.php
<?php

namespace App\Controller;

use App\Entity\Transaction;
use App\Form\TransactionType;
use App\Repository\TransactionRepository;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\JsonResponse;

class TransactionController extends Controller
{
    /**
     * @Route("/admin/transactions", name="transaction_index", methods={"GET"})
     */
    public function index(Request $request, TransactionRepository $transactionRepository): Response
    {

        $title_filter = '';

        if ($request->query->getAlnum('filter')) {
            $title_filter = $request->query->getAlnum('filter');
        }

        $paginator  = $this->get('knp_paginator');
        $pagination = $paginator->paginate(
            $transactionRepository->getPaginationQuery($title_filter),
            $request->query->getInt('page', 1),
            10
        );

        return $this->render('transaction/admin/index.html.twig', [
            'transactions' => $pagination,
        ]);
    }

    /**
     * @Route("/admin/transactions/new", name="transaction_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $transaction = new Transaction();
        $form = $this->createForm(TransactionType::class, $transaction);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($transaction);
            $entityManager->flush();

            return $this->redirectToRoute('transaction_index');
        }

        return $this->render('transaction/admin/new.html.twig', [
            'transaction' => $transaction,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="transaction_show", methods={"GET"})
     */
    public function show(Transaction $transaction): Response
    {
        return $this->render('transaction/admin/show.html.twig', [
            'transaction' => $transaction,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="transaction_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Transaction $transaction): Response
    {
        $form = $this->createForm(TransactionType::class, $transaction);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $transaction->setUpdatedAt(new \DateTime());

            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('transaction_index', [
                'id' => $transaction->getId(),
            ]);
        }

        return $this->render('transaction/admin/edit.html.twig', [
            'transaction' => $transaction,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="transaction_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Transaction $transaction): Response
    {
        if ($this->isCsrfTokenValid('delete'.$transaction->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($transaction);
            $entityManager->flush();
        }

        return $this->redirectToRoute('transaction_index');
    }

    /**
     * @Route("/", name="transaction_list", methods={"GET"})
     */
    public function home(Request $request, TransactionRepository $transactionRepository): Response
    {
        return $this->render('transaction/index.html.twig', [
            'currentMonth' => date('m/Y', time()),
        ]);
    }

    /**
     * @Route("/ajax/transactions", name="transaction_ajax_list", methods={"GET"})
     */
    public function ajaxList(Request $request, TransactionRepository $transactionRepository): Response
    {
        if (!$request->isXmlHttpRequest() || !$request->query->get('month')) {
            return new JsonResponse(array(
                'status' => 'Error',
                'message' => 'Error'),
            400);
        }

        $month = $request->query->get('month');

        $transactions           = $transactionRepository->getByMonth($month);
        $amountBeforeMonth      = $transactionRepository->getAmountBeforeMonth($month);
        $transactions_formatted = array();

        $output = 0;
        $input  = 0;
        $amountIncludingMonth  = 0;

        foreach($transactions as $transaction){

            if($transaction->getIsInput()){
                $input  += $transaction->getAmount();
            }else{
                $output += $transaction->getAmount();
            }

            $amountIncludingMonth += $transaction->getAmount();

            array_push($transactions_formatted, array(
                'id'    => '#' . $transaction->getId(),
                'title' => $transaction->getTitle(),
                'description' => $transaction->getDescription(),
                'amount' => $transaction->getAmount() . '€',
                'is_input' => $transaction->getIsInput() ? 'Entrée' : 'Sortie',
                'is_valid' => $transaction->getIsValid() ? 'Oui' : 'Non',
                'month' => $transaction->getCreatedAt()->format('m/Y')
            ));
        }

        if($amountBeforeMonth)
            $amountIncludingMonth += $amountBeforeMonth;

        // Send all this back to client
        return new JsonResponse(array(
            'status'        => 'OK',
            'transactions'  => $transactions_formatted,
            'input'  => number_format($input, 2) . '€',
            'output'  => number_format($output, 2) . '€',
            'amountBeforeMonth'  => $amountBeforeMonth ? number_format($amountBeforeMonth, 2) . '€' : '0.00€',
            'amountIncludingMonth'  => $amountIncludingMonth ? number_format($amountIncludingMonth, 2) . '€' : '0.00€',
        ),
        200);
    }
    
}

templates/transaction/admin/_delete_form.html.twig
<form class="d-inline-block" method="post" action="{{ path('transaction_delete', {'id': transaction.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ transaction.id) }}">
    <button class="btn btn-outline-danger">Supprimer</button>
</form>

templates/transaction/admin/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-primary">{{ button_label|default('Enregistrer') }}</button>
{{ form_end(form) }}

templates/transaction/admin/edit.html.twig
{% extends 'admin.html.twig' %}

{% block title %}Editer la transaction{% endblock %}

{% block body %}
    <h1>Editer la transaction</h1>

    {{ include('transaction/admin/_form.html.twig', {'button_label': 'Update'}) }}

    <br/><br/>
    <a href="{{ path('transaction_index') }}">Retour à la liste</a>
{% endblock %}

templates/transaction/admin/index.html.twig
{% extends 'admin.html.twig' %}

{% block title %}Administration - Transactions{% endblock %}

{% block body %}
    <h1>Transactions</h1>

    <div>
        <form class="form-inline" action="{{ path('transaction_index') }}" method="get">
            <div class="form-group mx-sm-3 mb-2">
                <input name="filter" type="text" class="form-control" placeholder="Chercher par titre">
            </div>
            <button type="submit" class="btn btn-primary mb-2">Go</button>
        </form>
    </div>

    <div class="table-responsive">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Titre</th>
                    <th>Description</th>
                    <th>Montant</th>
                    <th>Type</th>
                    <th>Valide?</th>
                    <th>Mois</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
            {% for transaction in transactions %}
                <tr>
                    <td>#{{ transaction.id }}</td>
                    <td>{{ transaction.title }}</td>
                    <td>{{ transaction.description }}</td>
                    <td>{{ transaction.amount }}</td>
                    <td>{{ transaction.isInput ? 'Entrée' : 'Sortie' }}</td>
                    <td>{{ transaction.isValid ? 'Oui' : 'Non' }}</td>
                    <td>{{ transaction.createdAt|date("m/Y") }}</td>
                    <td>
                        <!--a href="{{ path('transaction_show', {'id': transaction.id}) }}" class="btn btn-outline-primary">show</a-->
                        <a href="{{ path('transaction_edit', {'id': transaction.id}) }}" class="btn btn-outline-primary">Modifier</a>
                        {{ include('transaction/admin/_delete_form.html.twig') }}
                    </td>
                </tr>
            {% else %}
                <tr>
                    <td colspan="8">Pas de transaction</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>

    {# display navigation #}
    <div class="navigation float-right">
        {{ knp_pagination_render(transactions) }}
    </div>

    <a href="{{ path('transaction_new') }}" class="btn btn-success">Ajouter une transaction</a>
{% endblock %}

templates/transaction/admin/new.html.twig
{% extends 'admin.html.twig' %}

{% block title %}Ajouter une transaction{% endblock %}

{% block body %}
    <h1>Ajouter une transaction</h1>

    {{ include('transaction/admin/_form.html.twig') }}

    <br/><br/>
    <a href="{{ path('transaction_index') }}">Retour à la liste</a>
{% endblock %}

templates/transaction/admin/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Transaction{% endblock %}

{% block body %}
    <h1>Transaction</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ transaction.id }}</td>
            </tr>
            <tr>
                <th>Title</th>
                <td>{{ transaction.title }}</td>
            </tr>
            <tr>
                <th>Amount</th>
                <td>{{ transaction.amount }}</td>
            </tr>
            <tr>
                <th>Is_input</th>
                <td>{{ transaction.isInput ? 'Yes' : 'No' }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ transaction.description }}</td>
            </tr>
            <tr>
                <th>Is_valid</th>
                <td>{{ transaction.isValid ? 'Yes' : 'No' }}</td>
            </tr>
            <tr>
                <th>Is_output</th>
                <td>{{ transaction.isOutput ? 'Yes' : 'No' }}</td>
            </tr>
            <tr>
                <th>Created_at</th>
                <td>{{ transaction.createdAt ? transaction.createdAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Updated_at</th>
                <td>{{ transaction.updatedAt ? transaction.updatedAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('transaction_index') }}">back to list</a>

    <a href="{{ path('transaction_edit', {'id': transaction.id}) }}">edit</a>

    {{ include('transaction/_delete_form.html.twig') }}
{% endblock %}